

# tidy text format {#tidytextformat}  

```{r,message=F}
library(tidyverse)
library(tidytext)
library(janeaustenr)
```

```{r}
austen_books()
```



```{r}
original_books <- austen_books() %>%
  group_by(book) %>%
  mutate(linenumber = row_number(),
         chapter = cumsum(str_detect(text, regex("^chapter [\\divxlc]",
                                                 ignore_case = TRUE)))) %>%
  ungroup()

original_books
```


```{r}
original_books %>%
  unnest_tokens(word, text)
```

```{r,cache=T}
stop_words 

tidy_books <- original_books %>%
  unnest_tokens(word, text) %>% 
  anti_join(stop_words)

tidy_books
```


## gutenbergr   

```{r}
library(gutenbergr)
```

```{r,cache=T}
hgwells <- gutenberg_download(c(35, 36, 5230, 159))

hgwells

tidy_hgwells <- hgwells %>%
  unnest_tokens(word, text) %>%
  anti_join(stop_words)
```

```{r,cache=T}
bronte <- gutenberg_download(c(1260, 768, 969, 9182, 767))

tidy_bronte <- bronte %>%
  unnest_tokens(word, text) %>%
  anti_join(stop_words)
```



```{r,cache=T}
df <- bind_rows(mutate(tidy_bronte, author = "Brontë Sisters"),
                       mutate(tidy_hgwells, author = "H.G. Wells"), 
                       mutate(tidy_books, author = "Jane Austen")) %>% 
  mutate(word = str_extract(word, "[a-z']+")) %>%
  count(author, word) %>%
  group_by(author) %>% 
  mutate(proportion = n / sum(n))

df
```


```{r}
df %>% 
  select(-n) %>% 
  pivot_wider(names_from = author, values_from = proportion) %>%
  pivot_longer(names_to = "author", values_to = "proportion", `Brontë Sisters`:`H.G. Wells`)


frequency <- df %>% 
  select(-n) %>% 
  pivot_wider(names_from = author, values_from = proportion) %>%
  pivot_longer(names_to = "author", values_to = "proportion", `Brontë Sisters`:`H.G. Wells`) %>%
  janitor::clean_names()





ggplot(frequency, aes(x = proportion, y = jane_austen, color = abs(jane_austen - proportion))) +
  geom_abline(color = "gray40", lty = 2) +
  geom_jitter(alpha = 0.1, size = 2.5, width = 0.3, height = 0.3) +
  geom_text(aes(label = word), check_overlap = TRUE, vjust = 1.5) +
  scale_x_log10(labels = scales::percent) +
  scale_y_log10(labels = scales::percent) +
  scale_color_gradient(limits = c(0, 0.001), low = "darkslategray4", high = "gray75",
                        guide = FALSE) +
  facet_wrap(~ author, ncol = 2) +
  labs(y = "Jane Austen", x = NULL) + 
  theme_classic() 
```


