
https://www.hvitfeldt.me/blog/word-rank-slope-charts/
```{r}
library(tidyverse)
library(tidytext)
library(hcandersenr)
library(paletteer)
library(ggrepel)
```


```{r}
gender_words <- tribble(
  ~men, ~women,
  "he", "she",
  "his", "her",
  "man", "woman",
  "men", "women",
  "boy", "girl",
  "he's", "she's",
  "he'd", "she'd",
  "he'll", "she'll",
  "himself", "herself"
)

ordered_words <- hcandersen_en %>% 
  unnest_tokens(word, text) %>% 
  count(word, sort = TRUE) %>% 
  pull(word)
```

```{r}
gender_words_plot <- gender_words %>%
  mutate(male_index = match(men, ordered_words),
         female_index = match(women, ordered_words)) %>%
  mutate(slope = log10(male_index) - log10(female_index)) %>%
  pivot_longer(male_index:female_index,
               names_to = "index", values_to = "rank") %>%
  mutate(rank_log10 = log10(rank),
         label = ifelse(index == "male_index", men, women)) %>%
  mutate(index = factor(index, c("male_index", "female_index"), c("men", "women")))

limit <- max(abs(gender_words_plot$slope)) * c(-1, 1)
```



```{r}
gender_words_plot %>%
  ggplot(aes(index, rank, group = men, label = label)) +
  geom_line(aes(color = slope)) +
  geom_text_repel() + 
  scale_y_log10() + 
  guides(color = "none") +
  scale_color_distiller(type = "div", 
                        limit = limit,
                        palette = "Paired") +
  theme_minimal() +
  theme(panel.border = element_blank(), 
        panel.grid.major.x = element_blank(),
        plot.title.position = "plot") + 
  labs(title = "Masculine gendered words appeared more often in H.C. Andersen's fairy tales",
       x = NULL, 
       y = "Word Rank")
```

$$
rank^k * f = c \\
k\log{rank} + log(f) = log(c)
$$